let cities =["hyderabad","mumbai","kochi"];
cities.push("bangalore","vijayawada");
let length=cities.length;
console.log(length);
console.log(cities);
cities.unshift("delhi");
cities[1]="chennai";
cities.push("kolkata");
cities.pop();
cities.pop();
let len=cities.length;
console.log(len);
console.log(cities);
let arr1 =["hello","world"];
let arr2=[1,3,9,5,4,9,6];
let arr3=[...arr1,...arr2];
console.log(arr3);
let arr4 =['a','j','t','r','f'];
let arr5=[...arr3,...arr4];
console.log(arr5);